# Generated by Django 5.1.6 on 2025-06-11 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='courses', to='core.track'),
        ),
        migrations.AlterField(
            model_name='courselearningoutcome',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='core.course'),
        ),
        migrations.AlterField(
            model_name='coursesyllabus',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabuses', to='core.course'),
        ),
    ]
